modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/AzureZhen/dotHackWeapons/issues"
logoFile="logo.png"
[[mods]] 
modId="dothack"
version="${file.jarVersion}" 
displayName="dotHack Weapons"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dothack-hack-weapons" 
authors="AzureDoomC" 
description='''
Adds dotHack Weapons into Minecraft
'''