modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/AzureZhen/dotHackWeapons/issues"
logoFile="logo.png"
[[mods]] 
modId="dothack"
version="${file.jarVersion}" 
displayName="dotHack Weapons"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dothack-hack-weapons" 
authors="AzureZhen" 
description='''
Adds dotHack Weapons into Minecraft
'''
[[dependencies.dothack]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.2,)"
    ordering="NONE"
    side="BOTH"