package mod.azure.rcraft.util;

import java.util.HashMap;
import java.util.Map;

import org.apache.commons.lang3.tuple.ImmutablePair;
import org.apache.commons.lang3.tuple.Pair;

import electroblob.wizardry.constants.Element;
import electroblob.wizardry.constants.Tier;
import net.minecraft.item.Item;

public class EBWandMap {
	
	public static Item getWand(Tier tier, Element element){
		if(tier == null) throw new NullPointerException("The given tier cannot be null.");
		if(element == null) element = Element.MAGIC;
		return WAND_MAP.get(ImmutablePair.of(tier, element));
	}
	
	private static final Map<Pair<Tier, Element>, Item> WAND_MAP = new HashMap<>();
	
	private static <T> T placeholder(){ return null; }
	
	public static final Item wavemaster42 = placeholder();
	public static final Item wavemaster38 = placeholder(); 
	public static final Item wavemaster74 = placeholder();
	public static final Item wavemaster43 = placeholder(); 
	public static final Item wavemaster57 = placeholder(); 
	public static final Item wavemaster61 = placeholder(); 
	public static final Item wavemaster62 = placeholder(); 
	public static final Item wavemaster69 = placeholder(); 
	public static final Item wavemaster71 = placeholder();
	public static final Item wavemaster24 = placeholder(); 
	public static final Item wavemaster1 = placeholder(); 
	public static final Item shadowwarlock2 = placeholder(); 
	public static final Item wavemaster36 = placeholder(); 
	public static final Item wavemaster37 = placeholder(); 
	public static final Item wavemaster50 = placeholder();
	public static final Item wavemaster52 = placeholder(); 
	public static final Item wavemaster65 = placeholder(); 
	public static final Item wavemaster29 = placeholder(); 
	public static final Item wavemaster22 = placeholder(); 
	public static final Item wavemaster35 = placeholder(); 
	public static final Item wavemaster23 = placeholder();
	public static final Item wavemaster44 = placeholder(); 
	public static final Item wavemaster41 = placeholder(); 
	public static final Item wavemaster51 = placeholder(); 
	public static final Item wavemaster31 = placeholder();
	public static final Item wavemaster42p = placeholder(); 
	public static final Item wavemaster38p = placeholder(); 
	public static final Item wavemaster74p = placeholder();
	public static final Item wavemaster43p = placeholder(); 
	public static final Item wavemaster57p = placeholder(); 
	public static final Item wavemaster61p = placeholder(); 
	public static final Item wavemaster62p = placeholder(); 
	public static final Item wavemaster69p = placeholder(); 
	public static final Item wavemaster71p = placeholder();
	public static final Item wavemaster24p = placeholder(); 
	public static final Item wavemaster1p = placeholder(); 
	public static final Item shadowwarlock2p = placeholder(); 
	public static final Item wavemaster36p = placeholder(); 
	public static final Item wavemaster37p = placeholder(); 
	public static final Item wavemaster50p = placeholder();
	public static final Item wavemaster52p = placeholder(); 
	public static final Item wavemaster65p = placeholder(); 
	public static final Item wavemaster29p = placeholder(); 
	public static final Item wavemaster22p = placeholder(); 
	public static final Item wavemaster35p = placeholder(); 
	public static final Item wavemaster23p = placeholder();
	public static final Item wavemaster44p = placeholder(); 
	public static final Item wavemaster41p = placeholder(); 
	public static final Item wavemaster51p = placeholder(); 
	public static final Item wavemaster31p = placeholder();
	public static final Item wavemaster42a = placeholder(); 
	public static final Item wavemaster38a = placeholder(); 
	public static final Item wavemaster74a = placeholder();
	public static final Item wavemaster43a = placeholder(); 
	public static final Item wavemaster57a = placeholder(); 
	public static final Item wavemaster61a = placeholder(); 
	public static final Item wavemaster62a = placeholder(); 
	public static final Item wavemaster69a = placeholder(); 
	public static final Item wavemaster71a = placeholder();
	public static final Item wavemaster24a = placeholder(); 
	public static final Item wavemaster1a = placeholder(); 
	public static final Item shadowwarlock2a = placeholder(); 
	public static final Item wavemaster36a = placeholder(); 
	public static final Item wavemaster37a = placeholder(); 
	public static final Item wavemaster50a = placeholder();
	public static final Item wavemaster52a = placeholder(); 
	public static final Item wavemaster65a = placeholder(); 
	public static final Item wavemaster29a = placeholder(); 
	public static final Item wavemaster22a = placeholder(); 
	public static final Item wavemaster35a = placeholder(); 
	public static final Item wavemaster23a = placeholder();
	public static final Item wavemaster44a = placeholder(); 
	public static final Item wavemaster41a = placeholder(); 
	public static final Item wavemaster51a = placeholder(); 
	public static final Item wavemaster31a = placeholder();
	public static final Item wavemaster42m = placeholder(); 
	public static final Item wavemaster38m = placeholder(); 
	public static final Item wavemaster74m = placeholder();
	public static final Item wavemaster43m = placeholder(); 
	public static final Item wavemaster57m = placeholder(); 
	public static final Item wavemaster61m = placeholder(); 
	public static final Item wavemaster62m = placeholder(); 
	public static final Item wavemaster69m = placeholder(); 
	public static final Item wavemaster71m = placeholder();
	public static final Item wavemaster24m = placeholder(); 
	public static final Item wavemaster1m = placeholder(); 
	public static final Item shadowwarlock2m = placeholder(); 
	public static final Item wavemaster36m = placeholder(); 
	public static final Item wavemaster37m = placeholder(); 
	public static final Item wavemaster50m = placeholder();
	public static final Item wavemaster52m = placeholder(); 
	public static final Item wavemaster65m = placeholder(); 
	public static final Item wavemaster29m = placeholder(); 
	public static final Item wavemaster22m = placeholder(); 
	public static final Item wavemaster35m = placeholder(); 
	public static final Item wavemaster23m = placeholder();
	public static final Item wavemaster44m = placeholder(); 
	public static final Item wavemaster41m = placeholder(); 
	public static final Item wavemaster51m = placeholder(); 
	public static final Item wavemaster31m = placeholder();
	public static final Item wavemaster72 = placeholder();
	public static final Item wavemaster73 = placeholder();
	public static final Item harvestcleric1 = placeholder();
	public static final Item wavemaster20 = placeholder();
	public static final Item wavemaster34 = placeholder();
	public static final Item shadowwarlock10 = placeholder();
	public static final Item wavemaster72p = placeholder();
	public static final Item wavemaster73p = placeholder();
	public static final Item harvestcleric1p = placeholder();
	public static final Item wavemaster20p = placeholder();
	public static final Item wavemaster34p = placeholder();
	public static final Item shadowwarlock10p = placeholder();
	public static final Item wavemaster72a = placeholder();
	public static final Item wavemaster73a = placeholder();
	public static final Item harvestcleric1a = placeholder();
	public static final Item wavemaster20a = placeholder();
	public static final Item wavemaster34a = placeholder();
	public static final Item shadowwarlock10a = placeholder();
	public static final Item wavemaster72m = placeholder();
	public static final Item wavemaster73m = placeholder();
	public static final Item harvestcleric1m = placeholder();
	public static final Item wavemaster20m = placeholder();
	public static final Item wavemaster34m = placeholder();
	public static final Item shadowwarlock10m = placeholder();
	
	public static void populateWandMap(){

		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster42);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster38); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster74);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster43); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster57); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster61); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster62); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster69); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster71);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster24); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster1); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), shadowwarlock2); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster36); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster37); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster50);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster52); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster65); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster29); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster22); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster35); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster23);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster44); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster41); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster51); 
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.MAGIC), wavemaster31);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster42p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster38p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster74p);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster43p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster57p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster61p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster62p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster69p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster71p);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster24p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster1p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), shadowwarlock2p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster36p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster37p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster50p);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster52p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster65p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster29p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster22p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster35p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster23p);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster44p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster41p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster51p); 
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.MAGIC), wavemaster31p);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster42a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster38a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster74a);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster43a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster57a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster61a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster62a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster69a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster71a);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster24a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster1a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), shadowwarlock2a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster36a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster37a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster50a);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster52a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster65a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster29a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster22a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster35a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster23a);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster44a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster41a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster51a); 
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.MAGIC), wavemaster31a);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster42m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster38m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster74m);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster43m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster57m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster61m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster62m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster69m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster71m);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster24m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster1m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), shadowwarlock2m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster36m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster37m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster50m);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster52m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster65m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster29m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster22m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster35m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster23m);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster44m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster41m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster51m); 
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.MAGIC), wavemaster31m);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.ICE), wavemaster72);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.ICE), wavemaster73);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.ICE), harvestcleric1);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.ICE), wavemaster20);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.ICE), wavemaster34);
		WAND_MAP.put(ImmutablePair.of(Tier.NOVICE, Element.ICE), shadowwarlock10);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.ICE), wavemaster72p);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.ICE), wavemaster73p);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.ICE), harvestcleric1p);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.ICE), wavemaster20p);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.ICE), wavemaster34p);
		WAND_MAP.put(ImmutablePair.of(Tier.APPRENTICE, Element.ICE), shadowwarlock10p);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.ICE), wavemaster72a);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.ICE), wavemaster73a);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.ICE), harvestcleric1a);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.ICE), wavemaster20a);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.ICE), wavemaster34a);
		WAND_MAP.put(ImmutablePair.of(Tier.ADVANCED, Element.ICE), shadowwarlock10a);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.ICE), wavemaster72m);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.ICE), wavemaster73m);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.ICE), harvestcleric1m);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.ICE), wavemaster20m);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.ICE), wavemaster34m);
		WAND_MAP.put(ImmutablePair.of(Tier.MASTER, Element.ICE), shadowwarlock10m);
		
	}

}
