package mod.azure.rcraft.util;

import com.robertx22.api.MineAndSlashAPI;
import com.robertx22.config.non_mine_items.ConfigItem;
import com.robertx22.database.gearitemslots.Axe;
import com.robertx22.database.gearitemslots.Bow;
import com.robertx22.database.gearitemslots.Hammer;
import com.robertx22.database.gearitemslots.Staff;
import com.robertx22.database.gearitemslots.Sword;

public class MMORPGHandler {

	public MMORPGHandler() {
		MineAndSlashAPI.addCompatibleItem("rcraft:harvestcleric", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:harvestcleric1", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:harvestcleric2", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:harvestcleric3", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:harvestcleric4", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:harvestcleric5", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:harvestcleric6", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:harvestcleric7", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:harvestcleric8", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:macabredancer", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:macabredancer1", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:macabredancer2", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:macabredancer3", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:macabredancer4", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock1", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock2", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock3", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock4", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock5", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock6", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock7", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock8", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock9", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock10", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock11", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock12", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:shadowwarlock13", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster1", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster2", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster3", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster4", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster5", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster6", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster7", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster8", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster9", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster10", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster11", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster12", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster13", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster14", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster15", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster16", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster17", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster18", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster19", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster20", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster21", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster22", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster23", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster24", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster25", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster26", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster27", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster28", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster29", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster30", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster31", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster32", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster33", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster34", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster35", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster36", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster37", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster38", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster39", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster40", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster41", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster42", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:wavemaster43", new ConfigItem().setType(new Staff()));
		MineAndSlashAPI.addCompatibleItem("rcraft:heavyaxeman", new ConfigItem().setType(new Axe()));
		MineAndSlashAPI.addCompatibleItem("rcraft:lordpartizan", new ConfigItem().setType(new Hammer()));
		MineAndSlashAPI.addCompatibleItem("rcraft:longarm", new ConfigItem().setType(new Hammer()));
		MineAndSlashAPI.addCompatibleItem("rcraft:edgepunisher", new ConfigItem().setType(new Hammer()));
		MineAndSlashAPI.addCompatibleItem("rcraft:edgepunisher2", new ConfigItem().setType(new Hammer()));
		MineAndSlashAPI.addCompatibleItem("rcraft:heavyblade", new ConfigItem().setType(new Hammer()));
		MineAndSlashAPI.addCompatibleItem("rcraft:flickreaper", new ConfigItem().setType(new Hammer()));
		MineAndSlashAPI.addCompatibleItem("rcraft:blademaster", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:bladebrandier", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:dualswords", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:dualswords3", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:tribalgrappler", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:tribalgrappler2", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:tribalgrappler3", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:tribalgrappler4", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:twinblade", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:twinblade61", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:twinblade71", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:twinblade81", new ConfigItem().setType(new Sword()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner1", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner2", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner3", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner4", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner5", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner6", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner7", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner8", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner9", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner10", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner11", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner12", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner13", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner14", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner15", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner16", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:steamgunner17", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:dualgunner", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:dualgunner1", new ConfigItem().setType(new Bow()));
		MineAndSlashAPI.addCompatibleItem("rcraft:dualgunner2", new ConfigItem().setType(new Bow()));
	}
}
